worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    upstream spring_app {
        server app:8080;
    }

    server {
        listen 443 ssl;
        server_name _;
        # server_name myapp.local 172.17.216.194;

        ssl_certificate     /etc/nginx/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

        client_max_body_size 10M;

        location / {
            proxy_pass http://spring_app;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 60s;
            proxy_send_timeout    60s;
            proxy_read_timeout    60s;
        }
    }

    server {
        listen 80;
        server_name _;
        # server_name myapp.local 172.17.216.194;
        return 301 https://$host$request_uri;
    }
}