apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: {{ .Values.configmap.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.configmap.postgresUser | quote }}
