spring:
  application:
    name: crudStudent

  datasource:
    url: jdbc:postgresql://localhost:5432/iphoneDB
    username: postgres
    password: raksa-14
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true