apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: spring-app
  ports:
    - port: {{ .Values.springApp.servicePort }}
      targetPort: {{ .Values.springApp.port }}
