namespace: prod

springApp:
  image: phalraksa/spring-app
  tag: "latest"
  imagePullPolicy: Always
  replicas: 1
  port: 8080
  servicePort: 80
  profiles:
    active: prod
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  datasource:
    url: jdbc:postgresql://postgres:5432/iphoneDB
  readinessProbe:
    path: /actuator/health/readiness
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 5

  livenessProbe:
    path: /actuator/health/liveness
    initialDelaySeconds: 120
    periodSeconds: 15
    failureThreshold: 3
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

hpa:
  minReplicas: 1
  maxReplicas: 4
  cpuUtilization: 70

ingress:
  enabled: true
  className: nginx
  host: myapp.local
  path: /
  pathType: Prefix

postgres:
  image: postgres
  tag: "16-alpine"
  imagePullPolicy: Always
  replicas: 1
  port: 5432
  storage: 5Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

configmap:
  postgresDb: iphoneDB
  postgresUser: postgres

# Override this at install time with --set secret.postgresPassword=xxx
# Never commit real passwords here!
secret:
  postgresPassword: ""
